export { default as Home } from './Home'
export { default as About } from './About'
export { default as Services } from './Services'
export { default as CaseStudies } from './CaseStudies'
export { default as Pricing } from './Pricing'
export { default as Blog } from './Blog'
export { default as Testimonials } from './Testimonials'
export { default as Contact } from './Contact'
